import React from "react";
import { Document, Image, Page, StyleSheet, Text, View } from "@react-pdf/renderer";
import type { AnalysisFinding, Company, CompanyConfig, Incident, Locale, Measure, TenantUser } from "@/lib/types";

const styles = StyleSheet.create({
  page: {
    padding: 36,
    fontSize: 10,
    color: "#17202A",
    fontFamily: "Helvetica",
  },
  header: {
    paddingBottom: 14,
    marginBottom: 18,
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
  },
  title: {
    fontSize: 22,
    fontWeight: 700,
  },
  subtitle: {
    marginTop: 5,
    color: "#566573",
  },
  logo: {
    height: 36,
    objectFit: "contain",
  },
  section: {
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 13,
    fontWeight: 700,
    marginBottom: 8,
  },
  grid: {
    display: "flex",
    flexDirection: "row",
    gap: 8,
  },
  factBox: {
    flex: 1,
    border: "1 solid #DDE4EA",
    padding: 8,
    borderRadius: 3,
  },
  label: {
    color: "#566573",
    fontSize: 8,
    textTransform: "uppercase",
    marginBottom: 3,
  },
  value: {
    fontSize: 10,
    fontWeight: 700,
  },
  paragraph: {
    lineHeight: 1.45,
  },
  tableHeader: {
    display: "flex",
    flexDirection: "row",
    color: "#FFFFFF",
    fontWeight: 700,
  },
  tableRow: {
    display: "flex",
    flexDirection: "row",
    borderBottom: "1 solid #E5E7EB",
  },
  cell: {
    padding: 6,
    flex: 1,
  },
  footer: {
    position: "absolute",
    bottom: 24,
    left: 36,
    right: 36,
    borderTop: "1 solid #DDE4EA",
    paddingTop: 8,
    color: "#566573",
    fontSize: 8,
  },
});

const reportLabels: Record<Locale, {
  reportTitle: string;
  generatedBy: string;
  executiveSummary: string;
  dateTime: string;
  location: string;
  severity: string;
  pse: string;
  incidentFacts: string;
  victimDetail: string;
  severityRationale: string;
  findings: string;
  directCauses: string;
  underlyingCauses: string;
  rootCauses: string;
  contributingFactors: string;
  measures: string;
  category: string;
  measure: string;
  priority: string;
  due: string;
  status: string;
  lessonsLearned: string;
  reportDate: string;
  yes: string;
  no: string;
  notSpecified: string;
}> = {
  nl: {
    reportTitle: "Incidentrapport",
    generatedBy: "Opgesteld door",
    executiveSummary: "Managementsamenvatting",
    dateTime: "Datum / tijd",
    location: "Locatie",
    severity: "Ernst",
    pse: "PSE",
    incidentFacts: "Feiten",
    victimDetail: "Slachtoffer/letsel",
    severityRationale: "Onderbouwing ernst",
    findings: "Bevindingen oorzaakanalyse",
    directCauses: "Directe oorzaken",
    underlyingCauses: "Onderliggende oorzaken",
    rootCauses: "Basisoorzaken",
    contributingFactors: "Bijdragende factoren",
    measures: "MUOPO-maatregelen",
    category: "Categorie",
    measure: "Maatregel",
    priority: "Prioriteit",
    due: "Vervaldatum",
    status: "Status",
    lessonsLearned: "Geleerde lessen",
    reportDate: "Rapportdatum",
    yes: "Ja",
    no: "Nee",
    notSpecified: "Niet gespecificeerd",
  },
  en: {
    reportTitle: "Incident Report",
    generatedBy: "Generated by",
    executiveSummary: "Executive Summary",
    dateTime: "Date / Time",
    location: "Location",
    severity: "Severity",
    pse: "PSE",
    incidentFacts: "Incident Facts",
    victimDetail: "Victim/injury detail",
    severityRationale: "Severity rationale",
    findings: "Root Cause Analysis Findings",
    directCauses: "Direct causes",
    underlyingCauses: "Underlying causes",
    rootCauses: "Root causes",
    contributingFactors: "Contributing factors",
    measures: "MUOPO Measures",
    category: "Category",
    measure: "Measure",
    priority: "Priority",
    due: "Due",
    status: "Status",
    lessonsLearned: "Lessons Learned",
    reportDate: "Report date",
    yes: "Yes",
    no: "No",
    notSpecified: "Not specified",
  },
  fr: {
    reportTitle: "Rapport d'incident",
    generatedBy: "Rédigé par",
    executiveSummary: "Synthèse pour la direction",
    dateTime: "Date / heure",
    location: "Lieu",
    severity: "Gravité",
    pse: "PSE",
    incidentFacts: "Faits",
    victimDetail: "Victime/blessure",
    severityRationale: "Justification de la gravité",
    findings: "Constats de l'analyse des causes",
    directCauses: "Causes directes",
    underlyingCauses: "Causes sous-jacentes",
    rootCauses: "Causes racines",
    contributingFactors: "Facteurs contributifs",
    measures: "Mesures MUOPO",
    category: "Catégorie",
    measure: "Mesure",
    priority: "Priorité",
    due: "Échéance",
    status: "Statut",
    lessonsLearned: "Enseignements",
    reportDate: "Date du rapport",
    yes: "Oui",
    no: "Non",
    notSpecified: "Non spécifié",
  },
};

export function IncidentReportDocument({
  company,
  companyConfig,
  incident,
  finding,
  measures,
  author,
  executiveSummary,
  lessonsLearned,
  language,
}: {
  company: Company;
  companyConfig: Pick<CompanyConfig, "brandColor" | "footerText">;
  incident: Incident;
  finding: AnalysisFinding;
  measures: Measure[];
  author: TenantUser;
  executiveSummary: string;
  lessonsLearned: string[];
  language: Locale;
}) {
  const labels = reportLabels[language];
  const brand = companyConfig.brandColor || "#1B4F72";
  const showLogo = company.logoUrl.startsWith("http");

  return (
    <Document title={`${incident.referenceNumber} report`} author={author.fullName}>
      <Page size="A4" style={styles.page}>
        <View style={[styles.header, { borderBottom: `2 solid ${brand}` }]}>
          <View>
            <Text style={[styles.title, { color: brand }]}>{incident.referenceNumber} {labels.reportTitle}</Text>
            <Text style={styles.subtitle}>{company.name} · {labels.generatedBy} {author.fullName}</Text>
          </View>
          {/* eslint-disable-next-line jsx-a11y/alt-text -- react-pdf Image, not an HTML img */}
          {showLogo ? <Image style={styles.logo} src={company.logoUrl} /> : null}
        </View>

        <View style={styles.section}>
          <Text style={[styles.sectionTitle, { color: brand }]}>{labels.executiveSummary}</Text>
          <Text style={styles.paragraph}>{executiveSummary}</Text>
        </View>

        <View style={[styles.section, styles.grid]}>
          <View style={styles.factBox}><Text style={styles.label}>{labels.dateTime}</Text><Text style={styles.value}>{incident.incidentDate} {incident.incidentTime}</Text></View>
          <View style={styles.factBox}><Text style={styles.label}>{labels.location}</Text><Text style={styles.value}>{incident.location}</Text></View>
          <View style={styles.factBox}><Text style={styles.label}>{labels.severity}</Text><Text style={styles.value}>{incident.severityLevel}</Text></View>
          <View style={styles.factBox}><Text style={styles.label}>{labels.pse}</Text><Text style={styles.value}>{incident.isPse ? labels.yes : labels.no}</Text></View>
        </View>

        <View style={styles.section}>
          <Text style={[styles.sectionTitle, { color: brand }]}>{labels.incidentFacts}</Text>
          <Text style={styles.paragraph}>{incident.description}</Text>
          {incident.isVictim ? <Text style={styles.paragraph}>{labels.victimDetail}: {incident.injuryLocation ?? labels.notSpecified}.</Text> : null}
          <Text style={styles.paragraph}>{labels.severityRationale}: {incident.severityRationale}</Text>
        </View>

        <View style={styles.section}>
          <Text style={[styles.sectionTitle, { color: brand }]}>{labels.findings}</Text>
          <Text style={styles.paragraph}>{labels.directCauses}: {finding.directCauses.join("; ")}</Text>
          <Text style={styles.paragraph}>{labels.underlyingCauses}: {finding.underlyingCauses.join("; ")}</Text>
          <Text style={styles.paragraph}>{labels.rootCauses}: {finding.rootCauses.join("; ")}</Text>
          <Text style={styles.paragraph}>{labels.contributingFactors}: {finding.contributingFactors.join("; ")}</Text>
        </View>

        <View style={styles.section}>
          <Text style={[styles.sectionTitle, { color: brand }]}>{labels.measures}</Text>
          <View style={[styles.tableHeader, { backgroundColor: brand }]}>
            <Text style={styles.cell}>{labels.category}</Text>
            <Text style={[styles.cell, { flex: 3 }]}>{labels.measure}</Text>
            <Text style={styles.cell}>{labels.priority}</Text>
            <Text style={styles.cell}>{labels.due}</Text>
            <Text style={styles.cell}>{labels.status}</Text>
          </View>
          {measures.map((measure) => (
            <View key={measure.id} style={styles.tableRow}>
              <Text style={styles.cell}>{measure.muopoCategory}</Text>
              <Text style={[styles.cell, { flex: 3 }]}>{measure.description}</Text>
              <Text style={styles.cell}>{measure.priority}</Text>
              <Text style={styles.cell}>{measure.dueDate}</Text>
              <Text style={styles.cell}>{measure.status}</Text>
            </View>
          ))}
        </View>

        {lessonsLearned.length > 0 ? (
          <View style={styles.section}>
            <Text style={[styles.sectionTitle, { color: brand }]}>{labels.lessonsLearned}</Text>
            {lessonsLearned.map((lesson, index) => (
              <Text key={index} style={styles.paragraph}>• {lesson}</Text>
            ))}
          </View>
        ) : null}

        <Text style={styles.footer}>{companyConfig.footerText || "SafeTrack HSE"} · {labels.reportDate} {new Date().toISOString().slice(0, 10)}</Text>
      </Page>
    </Document>
  );
}
