import React from "react";
import { Document, Page, StyleSheet, Text, View } from "@react-pdf/renderer";
import type { AnalysisFinding, Company, Incident, Measure, TenantUser } from "@/lib/types";

const styles = StyleSheet.create({
  page: {
    padding: 36,
    fontSize: 10,
    color: "#17202A",
    fontFamily: "Helvetica",
  },
  header: {
    borderBottom: "2 solid #1B4F72",
    paddingBottom: 14,
    marginBottom: 18,
  },
  title: {
    fontSize: 22,
    color: "#1B4F72",
    fontWeight: 700,
  },
  subtitle: {
    marginTop: 5,
    color: "#566573",
  },
  section: {
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 13,
    color: "#1B4F72",
    fontWeight: 700,
    marginBottom: 8,
  },
  grid: {
    display: "flex",
    flexDirection: "row",
    gap: 8,
  },
  factBox: {
    flex: 1,
    border: "1 solid #DDE4EA",
    padding: 8,
    borderRadius: 3,
  },
  label: {
    color: "#566573",
    fontSize: 8,
    textTransform: "uppercase",
    marginBottom: 3,
  },
  value: {
    fontSize: 10,
    fontWeight: 700,
  },
  paragraph: {
    lineHeight: 1.45,
  },
  tableHeader: {
    display: "flex",
    flexDirection: "row",
    backgroundColor: "#1B4F72",
    color: "#FFFFFF",
    fontWeight: 700,
  },
  tableRow: {
    display: "flex",
    flexDirection: "row",
    borderBottom: "1 solid #E5E7EB",
  },
  cell: {
    padding: 6,
    flex: 1,
  },
  footer: {
    position: "absolute",
    bottom: 24,
    left: 36,
    right: 36,
    borderTop: "1 solid #DDE4EA",
    paddingTop: 8,
    color: "#566573",
    fontSize: 8,
  },
});

export function IncidentReportDocument({
  company,
  incident,
  finding,
  measures,
  author,
}: {
  company: Company;
  incident: Incident;
  finding: AnalysisFinding;
  measures: Measure[];
  author: TenantUser;
}) {
  return (
    <Document title={`${incident.referenceNumber} report`} author={author.fullName}>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>{incident.referenceNumber} Incident Report</Text>
          <Text style={styles.subtitle}>{company.name} · Generated by {author.fullName}</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Executive Summary</Text>
          <Text style={styles.paragraph}>
            {incident.title}. Severity {incident.severityLevel}. {incident.isPse ? "This incident is flagged as a Process Safety Event. " : ""}
            The investigation identified {finding.rootCauses.length} root cause(s) and {measures.length} corrective or preventive measure(s).
          </Text>
        </View>

        <View style={[styles.section, styles.grid]}>
          <View style={styles.factBox}><Text style={styles.label}>Date / Time</Text><Text style={styles.value}>{incident.incidentDate} {incident.incidentTime}</Text></View>
          <View style={styles.factBox}><Text style={styles.label}>Location</Text><Text style={styles.value}>{incident.location}</Text></View>
          <View style={styles.factBox}><Text style={styles.label}>Severity</Text><Text style={styles.value}>{incident.severityLevel}</Text></View>
          <View style={styles.factBox}><Text style={styles.label}>PSE</Text><Text style={styles.value}>{incident.isPse ? "Yes" : "No"}</Text></View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Incident Facts</Text>
          <Text style={styles.paragraph}>{incident.description}</Text>
          {incident.isVictim ? <Text style={styles.paragraph}>Victim/injury detail: {incident.injuryLocation ?? "Not specified"}.</Text> : null}
          <Text style={styles.paragraph}>Severity rationale: {incident.severityRationale}</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Root Cause Analysis Findings</Text>
          <Text style={styles.paragraph}>Direct causes: {finding.directCauses.join("; ")}</Text>
          <Text style={styles.paragraph}>Underlying causes: {finding.underlyingCauses.join("; ")}</Text>
          <Text style={styles.paragraph}>Root causes: {finding.rootCauses.join("; ")}</Text>
          <Text style={styles.paragraph}>Contributing factors: {finding.contributingFactors.join("; ")}</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>MUOPO Measures</Text>
          <View style={styles.tableHeader}>
            <Text style={styles.cell}>Category</Text>
            <Text style={[styles.cell, { flex: 3 }]}>Measure</Text>
            <Text style={styles.cell}>Priority</Text>
            <Text style={styles.cell}>Due</Text>
            <Text style={styles.cell}>Status</Text>
          </View>
          {measures.map((measure) => (
            <View key={measure.id} style={styles.tableRow}>
              <Text style={styles.cell}>{measure.muopoCategory}</Text>
              <Text style={[styles.cell, { flex: 3 }]}>{measure.description}</Text>
              <Text style={styles.cell}>{measure.priority}</Text>
              <Text style={styles.cell}>{measure.dueDate}</Text>
              <Text style={styles.cell}>{measure.status}</Text>
            </View>
          ))}
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Lessons Learned</Text>
          <Text style={styles.paragraph}>Temporary transfer setups require explicit verification, clear hose replacement criteria, and visible supervision before transfer starts.</Text>
        </View>

        <Text style={styles.footer}>SafeTrack HSE · Report date {new Date().toISOString().slice(0, 10)} · Confidential tenant data</Text>
      </Page>
    </Document>
  );
}
